version: '3.8'

services:
  # Main test runner service
  jbit-form-tests:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: jbit-form-tester
    environment:
      - NODE_ENV=production
      - CI=true
      - CUSTOMER=jbit
      # Override these in .env file for local development
      - HEADLESS=${HEADLESS:-true}
      - TIMEOUT=${TIMEOUT:-60000}
    volumes:
      # Mount reports directory to persist results
      - ./customers/jbit/reports:/app/customers/jbit/reports
      # Mount test results to host
      - ./test-results:/app/test-results
      # Optional: mount environment file
      - ./.env:/app/.env:ro
    networks:
      - testing-network
    # Resource limits to prevent container from consuming too much
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '1.0'
          memory: 1G
    # Auto-restart policy
    restart: unless-stopped
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Container is healthy')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Simple web server to serve reports locally
  report-server:
    image: nginx:alpine
    container_name: jbit-report-server
    ports:
      - "8080:80"
    volumes:
      - ./customers/jbit/reports/html-report:/usr/share/nginx/html:ro
      - ./config/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - testing-network
    depends_on:
      - jbit-form-tests
    # Only start if explicitly requested
    profiles:
      - reports

networks:
  testing-network:
    driver: bridge
    name: jbit-testing-network

# Named volumes for persistent data
volumes:
  test-reports:
    name: jbit-test-reports
  test-artifacts:
    name: jbit-test-artifacts